### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by Atomk** [wisonye/zig-tutorial-by-examples#1]
The repo does not specify a license. A license would make it easier for other people to contribute, and also makes clear how people can use the content and code examples.
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
- https://choosealicense.com/

**Comment by wisonye** [comment]
> The repo does not specify a license. A license would make it easier for other people to contribute, and also makes clear how people can use the content and code examples.
> 
> * https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
> * https://choosealicense.com/

Thanks, done already:)
